import { getSetting, setSetting } from "@/lib/branding";

/** Frases sobre trabajo en equipo para el cierre del correo. Se elige una distinta a la anterior. */
export const FRASES: string[] = [
  "Solos podemos hacer poco; juntos podemos hacer mucho.",
  "El talento gana partidos, pero el trabajo en equipo gana campeonatos.",
  "Si quieres ir rápido, camina solo; si quieres llegar lejos, camina acompañado.",
  "Un equipo no es un grupo de personas que trabajan juntas, sino que confían unas en otras.",
  "Reunirse es un comienzo, seguir juntos es un progreso y trabajar juntos es un éxito.",
  "Ninguno de nosotros es tan inteligente como todos nosotros juntos.",
  "Las grandes cosas en los negocios nunca las hace una sola persona; las hace un equipo.",
  "La unión hace la fuerza.",
  "Cuando todos reman en la misma dirección, el barco llega más lejos.",
  "El éxito es mejor cuando se comparte.",
  "Un buen equipo convierte las ideas en resultados.",
  "La colaboración convierte los retos en oportunidades.",
  "Cada persona suma; juntos multiplicamos.",
  "Los equipos fuertes se construyen con confianza, respeto y compromiso.",
  "Lo que hoy construimos en equipo, mañana lo celebramos juntos.",
  "Compartir el objetivo hace que el camino sea más ligero.",
  "El trabajo en equipo hace que el sueño funcione.",
  "Donde hay equipo, hay futuro.",
  "Un equipo comprometido es capaz de lo extraordinario.",
  "La suma de nuestras fortalezas supera cualquier obstáculo.",
  "Juntos logramos lo que por separado parece imposible.",
  "El equilibrio de un equipo está en valorar lo que cada quien aporta.",
  "Cuando el equipo se apoya, cada meta se vuelve alcanzable.",
  "Los grandes logros nacen de pequeñas colaboraciones.",
  "Un equipo unido avanza con paso firme.",
  "Trabajar en equipo es hacer que el objetivo de uno sea el de todos.",
  "La confianza es el pegamento de los equipos extraordinarios.",
  "Cada logro empieza con la decisión de intentarlo juntos.",
  "Del esfuerzo compartido nacen los mejores resultados.",
  "En equipo, los problemas se reparten y las victorias se multiplican.",
  "La diversidad de ideas es la fuerza de un buen equipo.",
  "Escuchar es la primera habilidad de quien trabaja en equipo.",
  "Un equipo que se comunica es un equipo que crece.",
  "Cuando alguien tropieza, el equipo lo levanta.",
  "El compromiso de cada uno es la fortaleza de todos.",
  "Los equipos extraordinarios se forman con personas que se importan.",
  "El mejor resultado es el que logramos acompañados.",
  "Una meta compartida es una meta más cercana.",
  "El trabajo en equipo es el combustible que permite a personas comunes alcanzar resultados no comunes.",
  "Con un propósito común, el esfuerzo se vuelve ligero.",
  "Juntos somos más creativos, más ágiles y más fuertes.",
  "El respeto mutuo es la base de cualquier gran equipo.",
  "Un equipo coordinado convierte la complejidad en claridad.",
  "Cada aporte cuenta, cada voz importa.",
  "Hacer equipo es avanzar al ritmo de todos sin perder el rumbo.",
  "El éxito de un proyecto se escribe con muchas manos.",
  "Los puentes se construyen entre varios, nunca solo.",
  "Cuando compartimos el reto, también compartimos la satisfacción.",
  "Un equipo alineado llega más rápido y con mejor calidad.",
  "La excelencia es el resultado de la colaboración constante.",
  "Las buenas ideas florecen cuando el equipo las cuida.",
  "Quien se suma al equipo, suma al resultado.",
  "El liderazgo se demuestra cuando todo el equipo crece.",
  "Un equipo se mide por lo que logra cuando trabaja unido.",
  "Hay metas que solo se alcanzan acompañados.",
  "Cuando hay confianza, hay resultados.",
  "La mejor estrategia es un equipo comprometido.",
  "Nuestra mayor fortaleza es la manera en que trabajamos juntos.",
  "La cooperación convierte el esfuerzo de muchos en el éxito de todos.",
  "Cuanto más compartimos, más aprendemos.",
  "Un equipo feliz hace clientes felices.",
  "Los retos compartidos se resuelven con ingenio colectivo.",
  "Cada proyecto exitoso empieza con un equipo dispuesto.",
  "La armonía de un equipo se nota en sus resultados.",
  "El camino es mejor cuando se recorre en compañía.",
  "Un equipo sólido transforma las dificultades en aprendizajes.",
  "Lo que logramos juntos tiene un valor que nadie logra solo.",
  "Cuando colaboramos, el límite lo ponemos nosotros.",
  "Los equipos que se celebran entre sí llegan más lejos.",
  "Cada colaborador es una pieza clave del rompecabezas.",
  "Con constancia y equipo, no hay meta lejana.",
  "El mayor activo de una empresa es su gente trabajando unida.",
  "Un equipo que aprende junto crece junto.",
  "La claridad en los objetivos une a los equipos.",
  "Hay fuerza en la unión y belleza en la colaboración.",
  "Un equipo comprometido convierte el trabajo en propósito.",
  "Con humildad y colaboración, los resultados llegan.",
  "Las personas hacen la diferencia; los equipos hacen la historia.",
  "El éxito nunca es un logro individual.",
  "Entre todos, cualquier meta pesa menos.",
  "Cuando el equipo confía, el cliente lo nota.",
  "Una idea compartida vale más que una idea guardada.",
  "Detrás de cada gran resultado hay un gran equipo.",
  "La cooperación es la clave que abre cualquier puerta.",
  "Sumar voluntades es la forma más inteligente de avanzar.",
  "Un equipo que comparte el esfuerzo comparte el triunfo.",
  "Las metas ambiciosas necesitan equipos decididos.",
  "Mejor juntos: es la fórmula que nunca falla.",
  "Cada día es una oportunidad de construir algo más grande entre todos.",
  "El entusiasmo de un equipo es contagioso.",
  "Cuando damos lo mejor de cada uno, el equipo da lo mejor de sí.",
  "Un equipo unido convierte los sueños en planes y los planes en logros.",
  "Cooperar es la manera más eficaz de competir.",
  "Con buena comunicación, los equipos hacen magia.",
  "Los resultados extraordinarios nacen de la colaboración cotidiana.",
  "Somos más fuertes cuando nos apoyamos.",
  "El éxito colectivo comienza con el compromiso individual.",
  "Un equipo diverso ve más posibilidades.",
  "Compartir conocimiento es multiplicar el valor del equipo.",
  "La dedicación de cada persona construye la grandeza del conjunto.",
  "Cuando el equipo se enfoca, el resultado llega.",
  "Un equipo que se cuida es un equipo que perdura.",
  "La mejor victoria es la que se celebra entre todos.",
  "Con cada proyecto entregado, el equipo se hace más fuerte.",
];

/** Elige una frase distinta a la última usada y la recuerda. */
export async function nextFrase(): Promise<string> {
  const last = Number((await getSetting("last_frase")) ?? -1);
  let i = Math.floor(Math.random() * FRASES.length);
  if (FRASES.length > 1 && i === last) i = (i + 1) % FRASES.length;
  await setSetting("last_frase", String(i)).catch(() => {});
  return FRASES[i];
}
